# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # Assurez-vous que la version de Python correspond à celle nécessaire pour votre projet

# Configuration pour Sphinx, car vous avez un dossier `docs` et un fichier `conf.py`
sphinx:
  configuration: docs/conf.py

# Commandes pour installer les dépendances et construire la documentation avec Sphinx
build:
  commands:
    - npm install
    - npm run build
    - sphinx-build -b html docs/ _build/html  # Build the documentation into the _build/html directory

# Génération des formats PDF et ePub si nécessaire
formats:
  - pdf
  - epub

# Déclaration des dépendances Python
python:
  install:
    - requirements: docs/requirements.txt  # Mettez le chemin correct vers votre fichier de requirements

# Assurez-vous que les extensions nécessaires pour Sphinx sont activées dans conf.py